// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9KYUkPrrhq72nwq2H15B6ynMD2jnFs34',
    appId: '1:682826960306:web:4a1ef73ffa56143c5168ab',
    messagingSenderId: '682826960306',
    projectId: 'healthconnect-ad0f1',
    authDomain: 'healthconnect-ad0f1.firebaseapp.com',
    storageBucket: 'healthconnect-ad0f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaNCRLsT9670SyOpwRpWw5MjiBKa2xVqQ',
    appId: '1:682826960306:android:41c89ba9c747c33d5168ab',
    messagingSenderId: '682826960306',
    projectId: 'healthconnect-ad0f1',
    storageBucket: 'healthconnect-ad0f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmj_eskaNJgpkIAg0uKDVqQCAh1rtoAvQ',
    appId: '1:682826960306:ios:1e6b09338d7303e45168ab',
    messagingSenderId: '682826960306',
    projectId: 'healthconnect-ad0f1',
    storageBucket: 'healthconnect-ad0f1.appspot.com',
    iosBundleId: 'com.example.healthConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmj_eskaNJgpkIAg0uKDVqQCAh1rtoAvQ',
    appId: '1:682826960306:ios:49b0f67d9b7c15575168ab',
    messagingSenderId: '682826960306',
    projectId: 'healthconnect-ad0f1',
    storageBucket: 'healthconnect-ad0f1.appspot.com',
    iosBundleId: 'com.example.healthConnect.RunnerTests',
  );
}
